@startuml
start
:User retrieves input by pressing a key in the Command Box;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([user pressed 'UP'])
    if () then ([previous input available])
        :Retrieve previous input;
        if () then ([input is invalid])
            :Change Command Box text to red;
        else ([input is valid])
            :Change Command Box text to white;
        endif
    else ([previous input not available])
        :No change to the Command Box;
    endif
else if () then ([user pressed 'DOWN'])
    if () then ([following input available])
        :Retrieve following input;
        if () then ([input is invalid])
            :Change Command Box text to red;
        else ([input is valid])
            :Change Command Box text to white;
        endif
    else ([following input not available])
        :Command Box is cleared;
    endif
else ([else])
    :Change Command Box text to white;
endif
stop

@enduml
